# frozen_string_literal: true

# This file generated automatically using rdf vocabulary format from http://rdvocab.info/ElementsGr2/
require 'rdf'
module RDF::Vocab
  # @!parse
  #   # Vocabulary for <http://rdvocab.info/ElementsGr2/>
  #   class RDAGR2 < RDF::StrictVocabulary
  #   end
  class RDAGR2 < RDF::StrictVocabulary('http://rdvocab.info/ElementsGr2/')
    # Ontology definition
    ontology :"http://rdvocab.info/ElementsGr2",
             "dc11:title": %(RDA Group 2 Elements \(deprecated\)),
             "skos:note": %(This was the provisional registration of the RDA Group 2 Element Vocabulary, managed by the DCMI/RDA Task Group. )

    # Property definitions
    property :addressOfTheCorporateBody,
             domain: 'http://rdvocab.info/uri/schema/FRBRentitiesRDA/CorporateBody',
             "http://metadataregistry.org/uri/profile/regap/name": %(addressOfTheCorporateBody),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Address of the corporate body (Deprecated)',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(The address of a corporate body’s headquarters or offices, or an e-mail or Internet address for the body. \(Deprecated\)),
             "skos:scopeNote": %(FRAD 4.3.),
             type: 'rdf:Property'
    property :addressOfThePerson,
             domain: 'http://rdvocab.info/uri/schema/FRBRentitiesRDA/Person',
             "http://metadataregistry.org/uri/profile/regap/name": %(addressOfThePerson),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Address of the person (Deprecated)',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(The address of a person’s place of residence, business, or employer, and/or an e-mail or Internet address. \(Deprecated\)),
             "skos:scopeNote": %(FRAD 4.1.),
             type: 'rdf:Property'
    property :affiliation,
             domain: 'http://rdvocab.info/uri/schema/FRBRentitiesRDA/Person',
             "http://metadataregistry.org/uri/profile/regap/name": %(affiliation),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Affiliation (Deprecated)',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(A group with which a person is affiliated or has been affiliated through employment, membership, cultural identity, etc. \(Deprecated\)),
             "skos:scopeNote": %(FRAD 4.1.),
             type: 'rdf:Property'
    property :associatedInstitution,
             domain: 'http://rdvocab.info/uri/schema/FRBRentitiesRDA/CorporateBody',
             "http://metadataregistry.org/uri/profile/regap/name": %(associatedInstitution),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Associated institution (Deprecated)',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(An institution commonly associated with a corporate body. \(Deprecated\)),
             type: 'rdf:Property'
    property :biographicalInformation,
             domain: 'http://rdvocab.info/uri/schema/FRBRentitiesRDA/Person',
             "http://metadataregistry.org/uri/profile/regap/name": %(biographicalInformation),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Biographical information (Deprecated)',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(Information pertaining to the life or history of a person. \(Deprecated\)),
             "skos:scopeNote": %(FRAD 4.1.),
             type: 'rdf:Property'
    property :corporateHistory,
             domain: 'http://rdvocab.info/uri/schema/FRBRentitiesRDA/CorporateBody',
             "http://metadataregistry.org/uri/profile/regap/name": %(corporateHistory),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Corporate history (Deprecated)',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(Information pertaining to the history of a corporate body. \(Deprecated\)),
             "skos:scopeNote": %(FRAD 4.3.),
             type: 'rdf:Property'
    property :countryAssociatedWithThePerson,
             domain: 'http://rdvocab.info/uri/schema/FRBRentitiesRDA/Person',
             "http://metadataregistry.org/uri/profile/regap/name": %(countryAssociatedWithThePerson),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Country associated with the person (Deprecated)',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(A country with which a person is identified. \(Deprecated\)),
             "skos:scopeNote": %(FRAD 4.1.),
             type: 'rdf:Property'
    property :dateAssociatedWithTheCorporateBody,
             domain: 'http://rdvocab.info/uri/schema/FRBRentitiesRDA/CorporateBody',
             "http://metadataregistry.org/uri/profile/regap/hasSubproperty": [%(rdagr2:dateOfConferenceEtc), %(rdagr2:dateOfEstablishment), %(rdagr2:dateOfTermination)],
             "http://metadataregistry.org/uri/profile/regap/name": %(dateAssociatedWithTheCorporateBody),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Date associated with the corporate body (Deprecated)',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(The date or range of dates on which a conference, etc., is held, or a date with which a corporate body is otherwise associated \(e.g., date of founding\). \(Deprecated\)),
             "skos:scopeNote": %(FRBR 4.7.4 and FRAD 4.3.),
             type: 'rdf:Property'
    property :dateAssociatedWithTheFamily,
             domain: 'http://rdvocab.info/uri/schema/FRBRentitiesRDA/Family',
             "http://metadataregistry.org/uri/profile/regap/name": %(dateAssociatedWithTheFamily),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Date associated with the family (Deprecated)',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(A significant date associated with a family. \(Deprecated\)),
             "skos:scopeNote": %(FRAD 4.2.),
             type: 'rdf:Property'
    property :dateAssociatedWithThePerson,
             domain: 'http://rdvocab.info/uri/schema/FRBRentitiesRDA/Person',
             "http://metadataregistry.org/uri/profile/regap/hasSubproperty": [%(rdagr2:dateOfBirth), %(rdagr2:dateOfDeath), %(rdagr2:periodOfActivityOfThePerson)],
             "http://metadataregistry.org/uri/profile/regap/name": %(dateAssociatedWithThePerson),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Date associated with the person (Deprecated)',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(A significant date associated with a person \(e.g., date of birth, date of death\). \(Deprecated\)),
             "skos:scopeNote": %(FRBR 4.6.2 and FRAD 4.1.),
             type: 'rdf:Property'
    property :dateOfBirth,
             domain: 'http://rdvocab.info/uri/schema/FRBRentitiesRDA/Person',
             "http://metadataregistry.org/uri/profile/regap/name": %(dateOfBirth),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Date of birth (Deprecated)',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(The year a person was born. Date of birth may also include the month and day of the person’s birth. \(Deprecated\)),
             subPropertyOf: 'rdagr2:DateAssociatedWithThePerson',
             type: 'rdf:Property'
    property :dateOfConferenceEtc,
             domain: 'http://rdvocab.info/uri/schema/FRBRentitiesRDA/CorporateBody',
             "http://metadataregistry.org/uri/profile/regap/name": %(dateOfConferenceEtc),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Date of conference, etc. (Deprecated)',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(The date or range of dates on which a conference, congress, meeting, exhibition, fair, festival, etc., was held. \(Deprecated\)),
             "skos:scopeNote": %(FRBR 4.7.4 and FRAD 4.3.),
             subPropertyOf: 'rdagr2:dateAssociatedWithTheCorporateBody',
             type: 'rdf:Property'
    property :dateOfDeath,
             domain: 'http://rdvocab.info/uri/schema/FRBRentitiesRDA/Person',
             "http://metadataregistry.org/uri/profile/regap/name": %(dateOfDeath),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Date of death (Deprecated)',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(The year a person died. Date of death may also include the month and day of the person’s death. \(Deprecated\)),
             "skos:scopeNote": %(FRBR 4.6.2 and FRAD 4.1.),
             subPropertyOf: 'rdagr2:DateAssociatedWithThePerson',
             type: 'rdf:Property'
    property :dateOfEstablishment,
             domain: 'http://rdvocab.info/uri/schema/FRBRentitiesRDA/CorporateBody',
             "http://metadataregistry.org/uri/profile/regap/name": %(dateOfEstablishment),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Date of establishment (Deprecated)',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(The date on which a corporate body was established or founded. \(Deprecated\)),
             "skos:scopeNote": %(FRBR 4.7.4 and FRAD 4.3.),
             subPropertyOf: 'rdagr2:dateAssociatedWithTheCorporateBody',
             type: 'rdf:Property'
    property :dateOfTermination,
             domain: 'http://rdvocab.info/uri/schema/FRBRentitiesRDA/CorporateBody',
             "http://metadataregistry.org/uri/profile/regap/name": %(dateOfTermination),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Date of termination (Deprecated)',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(The date on which a corporate body was terminated or dissolved. \(Deprecated\)),
             "skos:scopeNote": %(FRBR 4.7.4 and FRAD 4.3.),
             subPropertyOf: 'rdagr2:dateAssociatedWithTheCorporateBody',
             type: 'rdf:Property'
    property :dateOfUsage,
             domain: 'http://rdvocab.info/uri/schema/FRBRentitiesRDA/Name',
             "http://metadataregistry.org/uri/profile/regap/name": %(dateOfUsage),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Date of usage (Deprecated)',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(A date or range of dates associated with the use of the name designated as the preferred name for a person. \(Deprecated\)),
             type: 'rdf:Property'
    property :familyHistory,
             domain: 'http://rdvocab.info/uri/schema/FRBRentitiesRDA/Family',
             "http://metadataregistry.org/uri/profile/regap/name": %(familyHistory),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Family history (Deprecated)',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(Information pertaining to the history of a family. \(Deprecated\)),
             "skos:scopeNote": %(FRAD 4.2.),
             type: 'rdf:Property'
    property :fieldOfActivityOfTheCorporateBody,
             domain: 'http://rdvocab.info/uri/schema/FRBRentitiesRDA/CorporateBody',
             "http://metadataregistry.org/uri/profile/regap/name": %(fieldOfActivityOfTheCorporateBody),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Field of activity of the corporate body (Deprecated)',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(A field of business in which a corporate body is engaged, its area of competence, responsibility, jurisdiction, etc. \(Deprecated\)),
             "skos:scopeNote": %(FRAD 4.3.),
             type: 'rdf:Property'
    property :fieldOfActivityOfThePerson,
             domain: 'http://rdvocab.info/uri/schema/FRBRentitiesRDA/Person',
             "http://metadataregistry.org/uri/profile/regap/name": %(fieldOfActivityOfThePerson),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Field of activity of the person (Deprecated)',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(A field of endeavour, area of expertise, etc., in which a person is engaged or was engaged. \(Deprecated\)),
             "skos:scopeNote": %(FRBR 4.6.4 and FRAD 4.1.),
             type: 'rdf:Property'
    property :fullerFormOfName,
             "http://metadataregistry.org/uri/profile/regap/hasSubproperty": %(rdagr2:fullerFormOfNamePerson),
             "http://metadataregistry.org/uri/profile/regap/name": %(fullerFormOfName),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Fuller form of name (Deprecated)',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(The full form of a part of a name represented only by an initial or abbreviation in the form chosen as the preferred name, or a part of the name not included in the form chosen as the preferred name. \(Deprecated\)),
             "skos:scopeNote": %(FRBR 4.6.1 and FRAD 4.1.),
             type: 'rdf:Property'
    property :fullerFormOfNamePerson,
             domain: 'http://rdvocab.info/uri/schema/FRBRentitiesRDA/Person',
             "http://metadataregistry.org/uri/profile/regap/name": %(fullerFormOfNamePerson),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Fuller form of name (Person) (Deprecated)',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(The full form of a part of a name represented only by an initial or abbreviation in the form chosen as the preferred name, or a part of the name not included in the form chosen as the preferred name. \(Deprecated\)),
             subPropertyOf: 'rdagr2:fullerFormOfName',
             type: 'rdf:Property'
    property :gender,
             domain: 'http://rdvocab.info/uri/schema/FRBRentitiesRDA/Person',
             "http://metadataregistry.org/uri/profile/regap/name": %(gender),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Gender (Deprecated)',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(The gender with which a person identifies. \(Deprecated\)),
             "skos:scopeNote": %(FRAD 4.1.),
             type: 'rdf:Property'
    property :hereditaryTitle,
             domain: 'http://rdvocab.info/uri/schema/FRBRentitiesRDA/Family',
             "http://metadataregistry.org/uri/profile/regap/name": %(hereditaryTitle),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Hereditary title (Deprecated)',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(A title of nobility, etc., associated with a family. \(Deprecated\)),
             "skos:scopeNote": %(FRAD 4.2.),
             type: 'rdf:Property'
    property :identifierForTheCorporateBody,
             domain: 'http://rdvocab.info/uri/schema/FRBRentitiesRDA/CorporateBody',
             "http://metadataregistry.org/uri/profile/regap/name": %(identifierForTheCorporateBody),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Identifier for the corporate body (Deprecated)',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(A character string uniquely associated with a corporate body, or with a surrogate for a corporate body \(e.g., an authority record\), that serves to differentiate that corporate body from other corporate bodies. \(Deprecated\)),
             "skos:scopeNote": %(FRAD 5.2.),
             type: 'rdf:Property'
    property :identifierForTheFamily,
             domain: 'http://rdvocab.info/uri/schema/FRBRentitiesRDA/Family',
             "http://metadataregistry.org/uri/profile/regap/name": %(identifierForTheFamily),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Identifier for the family (Deprecated)',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(A character string uniquely associated with a family, or with a surrogate for a family \(e.g., an authority record\), that serves to differentiate that family from other families. \(Deprecated\)),
             "skos:scopeNote": %(FRAD 5.2.),
             type: 'rdf:Property'
    property :identifierForThePerson,
             domain: 'http://rdvocab.info/uri/schema/FRBRentitiesRDA/Person',
             "http://metadataregistry.org/uri/profile/regap/name": %(identifierForThePerson),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Identifier for the person (Deprecated)',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(A character string uniquely associated with a person, or with a surrogate for a person \(e.g., an authority record\), that serves to differentiate that person from other persons. \(Deprecated\)),
             type: 'rdf:Property'
    property :languageOfTheCorporateBody,
             domain: 'http://rdvocab.info/uri/schema/FRBRentitiesRDA/CorporateBody',
             "http://metadataregistry.org/uri/profile/regap/name": %(languageOfTheCorporateBody),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Language of the corporate body (Deprecated)',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(A language a corporate body uses in its communications. \(Deprecated\)),
             "skos:scopeNote": %(FRAD 4.3.),
             type: 'rdf:Property'
    property :languageOfThePerson,
             domain: 'http://rdvocab.info/uri/schema/FRBRentitiesRDA/Person',
             "http://metadataregistry.org/uri/profile/regap/name": %(languageOfThePerson),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Language of the person (Deprecated)',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(A language a person uses when writing for publication, broadcasting, etc. \(Deprecated\)),
             "skos:scopeNote": %(FRAD 4.1.),
             type: 'rdf:Property'
    property :locationOfConferenceEtc,
             domain: 'http://rdvocab.info/uri/schema/FRBRentitiesRDA/CorporateBody',
             "http://metadataregistry.org/uri/profile/regap/name": %(locationOfConferenceEtc),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Location of conference, etc. (Deprecated)',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(A local place in which a conference, congress, meeting, exhibition, fair, festival, etc., was held. \(Deprecated\)),
             subPropertyOf: 'rdagr2:placeAssociatedWithTheCorporateBody',
             type: 'rdf:Property'
    property :locationOfHeadquarters,
             domain: 'http://rdvocab.info/uri/schema/FRBRentitiesRDA/CorporateBody',
             "http://metadataregistry.org/uri/profile/regap/name": %(locationOfHeadquarters),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Location of headquarters (Deprecated)',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(A country, state, province, etc., or local place in which an organization has its headquarters. \(Deprecated\)),
             "skos:scopeNote": %(FRBR 4.7.3 and FRAD 4.3.),
             subPropertyOf: 'rdagr2:placeAssociatedWithTheCorporateBody',
             type: 'rdf:Property'
    property :name,
             domain: 'http://rdvocab.info/uri/schema/FRBRentitiesRDA/Agent',
             "http://metadataregistry.org/uri/profile/regap/hasSubproperty": %(http://rdaregistry.info/Elements/e/P20287),
             "http://metadataregistry.org/uri/profile/regap/name": %(name),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Name (Deprecated)',
             range: 'http://rdvocab.info/uri/schema/FRBRentitiesRDA/Name',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(\(Deprecated\)),
             type: 'rdf:Property'
    property :nameOfTheCorporateBody,
             domain: 'http://rdvocab.info/uri/schema/FRBRentitiesRDA/CorporateBody',
             "http://metadataregistry.org/uri/profile/regap/hasSubproperty": [%(rdagr2:preferredNameForTheCorporateBody), %(rdagr2:variantNameForTheCorporateBody)],
             "http://metadataregistry.org/uri/profile/regap/name": %(nameOfTheCorporateBody),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Name of the corporate body (Deprecated)',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(A word, character, or group of words and/or characters by which a corporate body is known. \(Deprecated\)),
             "skos:scopeNote": %(FRBR 4.7.1 and FRAD 5.2.),
             type: 'rdf:Property'
    property :nameOfTheFamily,
             domain: 'http://rdvocab.info/uri/schema/FRBRentitiesRDA/Family',
             "http://metadataregistry.org/uri/profile/regap/hasSubproperty": [%(rdagr2:preferredNameForTheFamily), %(rdagr2:variantNameForTheFamily)],
             "http://metadataregistry.org/uri/profile/regap/name": %(nameOfTheFamily),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Name of the family (Deprecated)',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(A word, character, or group of words and/or characters by which a family is known. \(Deprecated\)),
             "skos:scopeNote": %(FRAD 5.2.),
             type: 'rdf:Property'
    property :nameOfThePerson,
             domain: 'http://rdvocab.info/uri/schema/FRBRentitiesRDA/Person',
             "http://metadataregistry.org/uri/profile/regap/hasSubproperty": [%(rdagr2:preferredNameForThePerson), %(rdagr2:variantNameForThePerson)],
             "http://metadataregistry.org/uri/profile/regap/name": %(nameOfThePerson),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Name of the person (Deprecated)',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(A word, character, or group of words and/or characters by which a person is known. \(Deprecated\)),
             "skos:scopeNote": %(FRBR 4.6.1 and FRAD 5.2.),
             type: 'rdf:Property'
    property :note,
             "http://metadataregistry.org/uri/profile/regap/name": %(note),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Note (Deprecated)',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(An annotation providing additional information relating to data recorded in another element. \(Deprecated\)),
             type: 'rdf:Property'
    property :numberOfAConferenceEtc,
             domain: 'http://rdvocab.info/uri/schema/FRBRentitiesRDA/CorporateBody',
             "http://metadataregistry.org/uri/profile/regap/name": %(numberOfAConferenceEtc),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Number of a conference, etc. (Deprecated)',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(A designation of the sequencing of a conference, etc., within a series of conferences, etc. \(Deprecated\)),
             type: 'rdf:Property'
    property :otherDesignationAssociatedWithTheCorporateBody,
             domain: 'http://rdvocab.info/uri/schema/FRBRentitiesRDA/CorporateBody',
             "http://metadataregistry.org/uri/profile/regap/name": %(otherDesignationAssociatedWithTheCorporateBody),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Other designation associated with the corporate body (Deprecated)',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(A word, phrase, or abbreviation indicating incorporation or legal status of a corporate body, or any term serving to differentiate the body from other corporate bodies, persons, etc. \(Deprecated\)),
             "skos:scopeNote": %(FRBR 4.7.2, 4.7.5 and FRAD 4.3.),
             type: 'rdf:Property'
    property :otherDesignationAssociatedWithThePerson,
             domain: 'http://rdvocab.info/uri/schema/FRBRentitiesRDA/Person',
             "http://metadataregistry.org/uri/profile/regap/name": %(otherDesignationAssociatedWithThePerson),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Other designation associated with the person (Deprecated)',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(A term other than a title that is associated with a person’s name. \(Deprecated\)),
             "skos:scopeNote": %(FRBR 4.6.4 and FRAD 4.1.),
             type: 'rdf:Property'
    property :periodOfActivityOfThePerson,
             domain: 'http://rdvocab.info/uri/schema/FRBRentitiesRDA/Person',
             "http://metadataregistry.org/uri/profile/regap/name": %(periodOfActivityOfThePerson),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Period of activity of the person (Deprecated)',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(A date or range of dates indicative of the period in which a person was active in his or her primary field of endeavour. \(Deprecated\)),
             "skos:scopeNote": %(FRBR 4.6.2 and FRAD 4.1.),
             subPropertyOf: 'rdagr2:DateAssociatedWithThePerson',
             type: 'rdf:Property'
    property :placeAssociatedWithTheCorporateBody,
             domain: 'http://rdvocab.info/uri/schema/FRBRentitiesRDA/CorporateBody',
             "http://metadataregistry.org/uri/profile/regap/hasSubproperty": [%(rdagr2:locationOfConferenceEtc), %(rdagr2:locationOfHeadquarters)],
             "http://metadataregistry.org/uri/profile/regap/name": %(placeAssociatedWithTheCorporateBody),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Place associated with the corporate body (Deprecated)',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(A significant location associated with a corporate body \(e.g., location of a conference, etc., location of the headquarters of an organization\). \(Deprecated\)),
             "skos:scopeNote": %(FRBR 4.7.3 and FRAD 4.3.),
             type: 'rdf:Property'
    property :placeAssociatedWithTheFamily,
             domain: 'http://rdvocab.info/uri/schema/FRBRentitiesRDA/Family',
             "http://metadataregistry.org/uri/profile/regap/name": %(placeAssociatedWithTheFamily),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Place associated with the family (Deprecated)',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(A place where a family resides or has resided or has some connection. \(Deprecated\)),
             "skos:scopeNote": %(FRAD 4.2.),
             type: 'rdf:Property'
    property :placeOfBirth,
             domain: 'http://rdvocab.info/uri/schema/FRBRentitiesRDA/Person',
             "http://metadataregistry.org/uri/profile/regap/name": %(placeOfBirth),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Place of birth (Deprecated)',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(The town, city, province, state, and/or country in which a person was born. \(Deprecated\)),
             "skos:scopeNote": %(FRAD 4.1.),
             type: 'rdf:Property'
    property :placeOfDeath,
             domain: 'http://rdvocab.info/uri/schema/FRBRentitiesRDA/Person',
             "http://metadataregistry.org/uri/profile/regap/name": %(placeOfDeath),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Place of death (Deprecated)',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(The town, city, province, state, and/or country in which a person died. \(Deprecated\)),
             "skos:scopeNote": %(FRAD 4.1.),
             type: 'rdf:Property'
    property :placeOfResidence,
             domain: 'http://rdvocab.info/uri/schema/FRBRentitiesRDA/Person',
             "http://metadataregistry.org/uri/profile/regap/name": %(placeOfResidence),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Place of residence (Deprecated)',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(A town, city, province, state, and/or country in which a person resides or has resided. \(Deprecated\)),
             "skos:scopeNote": %(FRAD 4.1.),
             type: 'rdf:Property'
    property :preferredNameForTheCorporateBody,
             domain: 'http://rdvocab.info/uri/schema/FRBRentitiesRDA/CorporateBody',
             "http://metadataregistry.org/uri/profile/regap/name": %(preferredNameForTheCorporateBody),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Preferred name for the corporate body (Deprecated)',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(The name or form of name chosen as the basis for the authorized access point representing that body. \(Deprecated\)),
             "skos:scopeNote": %(FRBR 4.6.1 and FRAD 5.2.),
             subPropertyOf: 'rdagr2:nameOfTheCorporateBody',
             type: 'rdf:Property'
    property :preferredNameForTheFamily,
             domain: 'http://rdvocab.info/uri/schema/FRBRentitiesRDA/Family',
             "http://metadataregistry.org/uri/profile/regap/name": %(preferredNameForTheFamily),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Preferred name for the family (Deprecated)',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(The name or form of name chosen as the basis for the authorized access point representing that family. \(Deprecated\)),
             "skos:scopeNote": %(FRAD 5.2.),
             subPropertyOf: 'rdagr2:nameOfTheFamily',
             type: 'rdf:Property'
    property :preferredNameForThePerson,
             domain: 'http://rdvocab.info/uri/schema/FRBRentitiesRDA/Person',
             "http://metadataregistry.org/uri/profile/regap/name": %(preferredNameForThePerson),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Preferred name for the person (Deprecated)',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(The name or form of name chosen as the basis for the authorized access point representing that person. \(Deprecated\)),
             "skos:scopeNote": %(FRBR 4.6.1 and FRAD 5.2.),
             subPropertyOf: 'rdagr2:nameOfThePerson',
             type: 'rdf:Property'
    property :professionOrOccupation,
             domain: 'http://rdvocab.info/uri/schema/FRBRentitiesRDA/Person',
             "http://metadataregistry.org/uri/profile/regap/name": %(professionOrOccupation),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Profession or occupation (Deprecated)',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(A profession or occupation in which a person works or has worked. \(Deprecated\)),
             "skos:scopeNote": %(FRAD 4.1.),
             type: 'rdf:Property'
    property :prominentMemberOfTheFamily,
             domain: 'http://rdvocab.info/uri/schema/FRBRentitiesRDA/Family',
             "http://metadataregistry.org/uri/profile/regap/name": %(prominentMemberOfTheFamily),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Prominent member of the family (Deprecated)',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(A well-known individual who is a member of a family. \(Deprecated\)),
             "skos:scopeNote": %(FRAD 4.2.),
             type: 'rdf:Property'
    property :scopeOfUsage,
             domain: 'http://rdvocab.info/uri/schema/FRBRentitiesRDA/Name',
             "http://metadataregistry.org/uri/profile/regap/name": %(scopeOfUsage),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Scope of usage (Deprecated)',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(The type or form of work associated with the name designated as the preferred name for a person, family, or corporate body. \(Deprecated\)),
             type: 'rdf:Property'
    property :titleOfThePerson,
             domain: 'http://rdvocab.info/uri/schema/FRBRentitiesRDA/Person',
             "http://metadataregistry.org/uri/profile/regap/name": %(titleOfThePerson),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Title of the person (Deprecated)',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(A word or phrase indicative of royalty, nobility, or ecclesiastical rank or office, or a term of address for a person of religious vocation. \(Deprecated\)),
             "skos:scopeNote": %(FRBR 4.6.3 and FRAD 4.1.),
             type: 'rdf:Property'
    property :typeOfFamily,
             domain: 'http://rdvocab.info/uri/schema/FRBRentitiesRDA/Family',
             "http://metadataregistry.org/uri/profile/regap/name": %(typeOfFamily),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Type of family (Deprecated)',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(A categorization or generic descriptor for the type of family. \(Deprecated\)),
             type: 'rdf:Property'
    property :undifferentiatedNameIndicator,
             "http://metadataregistry.org/uri/profile/regap/hasSubproperty": [%(rdagr2:undifferentiatedNameIndicatorCorporateBody), %(rdagr2:undifferentiatedNameIndicatorFamily), %(rdagr2:undifferentiatedNameIndicatorPerson)],
             "http://metadataregistry.org/uri/profile/regap/name": %(undifferentiatedNameIndicator),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Undifferentiated name indicator (Deprecated)',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(A categorization indicating that the core elements recorded are insufficient to differentiate between two or more entities with the same name. \(Deprecated\)),
             type: 'rdf:Property'
    property :undifferentiatedNameIndicatorCorporateBody,
             domain: 'http://rdvocab.info/uri/schema/FRBRentitiesRDA/CorporateBody',
             "http://metadataregistry.org/uri/profile/regap/name": %(undifferentiatedNameIndicatorCorporateBody),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Undifferentiated name indicator (Corporate Body) (Deprecated)',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(A categorization indicating that the core elements recorded are insufficient to differentiate between two or more corporate bodies with the same name. \(Deprecated\)),
             subPropertyOf: 'rdagr2:undifferentiatedNameIndicator',
             type: 'rdf:Property'
    property :undifferentiatedNameIndicatorFamily,
             domain: 'http://rdvocab.info/uri/schema/FRBRentitiesRDA/Family',
             "http://metadataregistry.org/uri/profile/regap/name": %(undifferentiatedNameIndicatorFamily),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Undifferentiated name indicator (Family) (Deprecated)',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(A categorization indicating that the core elements recorded are insufficient to differentiate between two or more families with the same name. \(Deprecated\)),
             subPropertyOf: 'rdagr2:undifferentiatedNameIndicator',
             type: 'rdf:Property'
    property :undifferentiatedNameIndicatorPerson,
             domain: 'http://rdvocab.info/uri/schema/FRBRentitiesRDA/Person',
             "http://metadataregistry.org/uri/profile/regap/name": %(undifferentiatedNameIndicatorPerson),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Undifferentiated name indicator (Person) (Deprecated)',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(A categorization indicating that the core elements recorded are insufficient to differentiate between two or more persons with the same name. \(Deprecated\)),
             subPropertyOf: 'rdagr2:undifferentiatedNameIndicator',
             type: 'rdf:Property'
    property :variantNameForTheCorporateBody,
             domain: 'http://rdvocab.info/uri/schema/FRBRentitiesRDA/CorporateBody',
             "http://metadataregistry.org/uri/profile/regap/name": %(variantNameForTheCorporateBody),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Variant name for the corporate body (Deprecated)',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(A name or form of name by which a corporate body is known that differs from the name or form of name chosen as the preferred name. \(Deprecated\)),
             subPropertyOf: 'rdagr2:nameOfTheCorporateBody',
             type: 'rdf:Property'
    property :variantNameForTheFamily,
             domain: 'http://rdvocab.info/uri/schema/FRBRentitiesRDA/Family',
             "http://metadataregistry.org/uri/profile/regap/name": %(variantNameForTheFamily),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Variant name for the family (Deprecated)',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(A name or form of name by which a family is known that differs from the name or form of name chosen as the preferred name. \(Deprecated\)),
             subPropertyOf: 'rdagr2:nameOfTheFamily',
             type: 'rdf:Property'
    property :variantNameForThePerson,
             domain: 'http://rdvocab.info/uri/schema/FRBRentitiesRDA/Person',
             "http://metadataregistry.org/uri/profile/regap/name": %(variantNameForThePerson),
             "http://metadataregistry.org/uri/profile/regap/status": %(http://metadataregistry.org/uri/RegStatus/1008),
             label: 'Variant name for the person (Deprecated)',
             "rdfs:isDefinedBy": %(http://rdvocab.info/ElementsGr2),
             "skos:definition": %(A name or form of name by which a person is known that differs from the name or form of name chosen as the preferred name. \(Deprecated\)),
             subPropertyOf: 'rdagr2:nameOfThePerson',
             type: 'rdf:Property'
  end
end
