version: "3"
services:
  minio:
    image: minio/minio:RELEASE.2018-09-01T00-38-25Z
    ports:
    - "3001:9000"
    command: server /data
    volumes:
    - ../tmp/minio:/data
  mongodb:
    image: mongo
    ports:
    - "3002:27017"
  redis:
    image: bitnami/redis
    environment:
    - ALLOW_EMPTY_PASSWORD=yes
    ports:
    - "3003:6379"
