<%
mongodb_uri = Mongo::URI.new(ENV['MONGODB_URL'] || 'mongodb://localhost')
%>
base: &base
  clients:
    default:
      database: <%= mongodb_uri.database %>
      hosts:
      <% mongodb_uri.servers.each do |server| %>
        - <%= server %>
      <% end %>
      options:
        user: <%= mongodb_uri.credentials[:user] %>
        password: <%= mongodb_uri.credentials[:password] %>
        auth_source: <%= mongodb_uri.uri_options['auth_source'] %>
        ssl: <%= mongodb_uri.uri_options['ssl'].to_s %>
        <% if File.exists?(File.join(Rails.root, 'config', 'mongodb-ssl-ca.crt')) %>
        ssl_ca_cert: <%= File.join(Rails.root, 'config', 'mongodb-ssl-ca.crt') %>
        <% end %>
  options:
    log_level: :warn
development:
  <<: *base
test:
  <<: *base
production:
  <<: *base
